server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://localhost:8081
          predicates:
            - Path=/payments/** 
        - id: room
          uri: http://localhost:8082
          predicates:
            - Path=/rooms/** 
        - id: mypage
          uri: http://localhost:8083
          predicates:
            - Path= /guestManagementPages/**
        - id: book
          uri: http://localhost:8084
          predicates:
            - Path=/books/** 
        - id: alarm
          uri: http://localhost:8085
          predicates:
            - Path=/notifications/** 
        - id: marketing
          uri: http://localhost:8086
          predicates:
            - Path=/marketings/** 
        - id: serviceCenter
          uri: http://localhost:8087
          predicates:
            - Path=/serviceCenters/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/payments/** 
        - id: room
          uri: http://room:8080
          predicates:
            - Path=/rooms/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /guestManagementPages/**
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/** 
        - id: alarm
          uri: http://alarm:8080
          predicates:
            - Path=/notifications/** 
        - id: marketing
          uri: http://marketing:8080
          predicates:
            - Path=/marketings/** 
        - id: serviceCenter
          uri: http://serviceCenter:8080
          predicates:
            - Path=/serviceCenters/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080